### ISSUE TITLE
question about high-resolution features

### ISSUE THREAD

**Issue by wmkai** [facebookresearch/Mask2Former#101]
Hello, @bowenc0221 
I want to use fixed-resolution features as the input to the transformer decoder. Can this be implemented by just modifying config file? thanks!

**Comment by bowenc0221** [comment]
What do you mean by "fixed-resolution features"? Do you mean the features in MaskFormer?

All ablation settings are not supported in this code and you have to modify the code yourself to perform such experiments.

**Comment by wmkai** [comment]
> What do you mean by "fixed-resolution features"? Do you mean the features in MaskFormer?
> 
> All ablation settings are not supported in this code and you have to modify the code yourself to perform such experiments.

OK, thanks for you reply.
