### ISSUE TITLE
Question about the need of bounding boxes in the labels

### ISSUE THREAD

**Issue by EnnioEvo** [facebookresearch/Mask2Former#12]
Hi, thank you for sharing your work, works greatly on my dataset.

I don't get if the model uses the ground truth of the bounding boxes:
for example, let's say we are working with the Coco dataset, would it change anything in the training phase if we switched every `annotations[n].segments_info[m].bbox` into `[0,0,0,0] `?

**Comment by bowenc0221** [comment]
No, the model never uses bounding boxes and it won't affect anything.

**Comment by EnnioEvo** [comment]
ok thank you
