### ISSUE TITLE
Converting a PyTorch model to an ONNX model

### ISSUE THREAD

**Issue by tprdk** [facebookresearch/Mask2Former#13]
Hi, thanks for your great work.
Currently I'm using coco maskformer2_swin_large_IN21k_384_bs16_100ep.yaml configuration with pretrained model.
I'm trying to convert this model to onnx format. But it gives me segmentation fault error.

Could you please share the converted model or inform about how to do it?

**Comment by bowenc0221** [comment]
This project is for research purpose only and we have never tried to convert it to onnx. Please reach out to Detectron2 team or PyTorch team for further help.

**Comment by tprdk** [comment]
Thanks for your reply.
