### ISSUE TITLE
For instance segmentation, how to deal with the 100 predicted instances for evalution?

### ISSUE THREAD

**Issue by Sunting78** [facebookresearch/Mask2Former#14]
There are 100 instances per image, how to post-process these instances? Is there any threshold or NMS? Where is the code for this part? Thanks.

**Comment by bowenc0221** [comment]
No threshold or NMS is used, we simply keep the top-K instances with the highest scores:

https://github.com/facebookresearch/Mask2Former/blob/46af009b115ca552b27f2a87adc571cb4be5cdbd/mask2former/maskformer_model.py#L344-L380

**Comment by tsrobcvai** [comment]
> test_topk_per_image
Thank you, what is the default setting for this value <test_topk_per_image>?  I am sorry, I didn't find it.

**Comment by JinsongLv** [comment]
It's a little bit weird. I tried to filter out predictions with low confidence for instance segmentation task, but it produced poorer results than not using any threshold.
