### ISSUE TITLE
Where can I download the initial model weights to train from scratch?

### ISSUE THREAD

**Issue by rgkannan676** [facebookresearch/Mask2Former#145]
Hi,

Thank you for this great repository.
Can you please advise from where I can download the initial weights mentioned in the config files? 
For eg: I was not able to find "swin_base_patch4_window12_384.pkl"  mentioned in the config file 'Mask2Former/configs/coco/instance-segmentation/swin/maskformer2_swin_base_384_bs16_50ep.yaml' for training from scratch.

I could only find the pre-trained models in [Mask2Former Model Zoo](https://github.com/facebookresearch/Mask2Former/blob/main/MODEL_ZOO.md). 

Thanks.

**Comment by rgkannan676** [comment]
I was able to find the models in - https://github.com/SwinTransformer/storage/releases/tag/v1.0.0 , is these the correct files?

**Comment by bowenc0221** [comment]
https://github.com/facebookresearch/Mask2Former/blob/main/tools/README.md

**Comment by rgkannan676** [comment]
Thank you.
