### ISSUE TITLE
Hello, when I run train_net_video.py to evaluate the vis model, it shows Annotations are not available for evaluation. 

### ISSUE THREAD

**Issue by hekaijie123** [facebookresearch/Mask2Former#170]
Hello, when I run train_net_video.py to evaluate the vis model, it shows Annotations are not available for evaluation. The output/inference/instances_predictions.pth and the output/inference results. Json is 2.1 G size. Specifically, what do I need to do to get the results?

**Comment by hekaijie123** [comment]
@wenhe-jia

**Comment by Chan0081** [comment]
Hi, how do you solve the problem?

**Comment by raiyaan-abdullah** [comment]
@hekaijie123 What was the solution?

**Comment by XingtongGe** [comment]
Hi, I also encountered this issue; could you share how you resolved it？
