### ISSUE TITLE
About ytvis_2021 dataset

### ISSUE THREAD

**Issue by hardyho** [facebookresearch/Mask2Former#20]
Hi, I am following up on your work on video instance segmentation and trying to run experiments on the ytvis_2021 dataset. The original data downloaded from the link is organized as:
```
{train/valid/test}/
    JPEGImages/
    instance.json
```
How should I convert it to the structure you used here? I just copied the `instance.json` as `train/valid/test.json`, evaluation could run correctly, but there were some file-not-found errors during training. Looks like some videos listed in `train/instance.json` are not included in `train/JPEGImages/`. What should I do?

Thanks a lot!

**Comment by bowenc0221** [comment]
I did not do any processing other than directly copying the json file:
```
train/instance.json => train.json
valid/instance.json => valid.json
test/instance.json => test.json
```

**Comment by hardyho** [comment]
Thanks!
