### ISSUE TITLE
Question for input data

### ISSUE THREAD

**Issue by tpark16** [facebookresearch/Mask2Former#22]
Hi, I really enjoyed reading Mask2Former paper.

Could 3d image be used for training if appropriate modification is done on code?

Regards,
Tae

**Comment by bowenc0221** [comment]
Yes, I believe if you replace the current backbone and pixel decoder with a 3D counterpart, the model will be able to do 3D segmentation.

I already verified its ability on video segmentation (check https://arxiv.org/abs/2112.10764) where the input is also 3D (but in X, Y, T instead of X, Y, Z).

**Comment by tpark16** [comment]
Thank you for quick reply. I’ll try to replace them.
