### ISSUE TITLE
attn_mask[torch.where(attn_mask.sum(-1) == attn_mask.shape[-1])] = False

### ISSUE THREAD

**Issue by dawang-11** [facebookresearch/Mask2Former#249]
when i try to train myself dataset with this model,i met this issue, and i have solved this,can someone help me.
![Uploading image.png…]()

**Comment by q1556450920** [comment]
The image seems to have failed to upload. Can you upload it again? thank you

**Comment by dawang-11** [comment]
> The image seems to have failed to upload. Can you upload it again? thank you

thank you,i solved this problem
