### ISSUE TITLE
A question regarding pixel decoder with Fapn

### ISSUE THREAD

**Issue by blossom1923** [facebookresearch/Mask2Former#25]
What confused me a lot is the pixel decoder as you mentioned briefly in the paper in one of the experiments said “Swin-L-FaPN uses FaPN as pixel decoder”, I have the strong desire to know exactly how do you use the FaPN as the pixel decoder as FaPN itself is the complete model? If you incorporate the FaPN components——FeatureAlign and FeatureSelectionModule to the pixel decoder of Mask2Former in one of the experiments?

**Comment by bowenc0221** [comment]
The FaPN is used to replace FPN as pixel decoder the same way as the original FaPN paper.
