### ISSUE TITLE
About evaluation Mask2Former on YouTubeVIS-2021

### ISSUE THREAD

**Issue by nlpcvai** [facebookresearch/Mask2Former#26]
The original data downloaded from the link is organized as:

> ytvis_2021/
     {train/valid/test}/
        JPEGImages/
        instance.json

There are no Annotations as you mentioned like below,

> ytvis_2021/
    {train,valid,test}.json
    {train,valid,test}/
      Annotations/
      JPEGImages/

How do you evaluation Mask2Former on YouTubeVIS-2021?

**Comment by bowenc0221** [comment]
Please see issue #20, json files for 2021 data are under `{train,valid,test}/` folders.

**Comment by Nanami18** [comment]
> Please see issue #20, json files for 2021 data are under `{train,valid,test}/` folders.

Are we expected to generate the Annotation folder from the json file by ourselves? I followed the above procedure to generate the json files, but when I tried to evaluate the performance using train_net_video.py with --eval-only flag turned on, the logger outputs "Annotations are not available for evaluation". Thanks for any input in advance :)

**Comment by Chan0081** [comment]
I have the same "Annotations are not available for evaluation" problem. Does anyone know how to solve it?
