### ISSUE TITLE
how to finetuning on custom dataset?

### ISSUE THREAD

**Issue by luolugithub** [facebookresearch/Mask2Former#27]
how to finetuning on custom dataset? is there any config file surport fintune

**Comment by bowenc0221** [comment]
You will need to first register custom dataset in Detectron2 following this document: https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html

Then you can change the `MODEL.WEIGHTS` filed in the config to the corresponding checkpoint you want to initialize the model.
