### ISSUE TITLE
Question about Bounding Box

### ISSUE THREAD

**Issue by JingukKim** [facebookresearch/Mask2Former#29]
Thanks for your great work!

For more general model, I think the model can infer bounding box too. 
So, I have two questions about your work.
1. Is there any reason why you didn't add module for infering bounding box?
2. I think just adding box_embed module after decoder like class_embed enables infering bounding box. Have you tired it? or you already tried but not working?

Thanks a lot!

**Comment by bowenc0221** [comment]
In this work we care about image segmentation and predicting bounding boxes is not necessary for getting segmentation masks in our model (we aim for a simple architecture and predicting bounding boxes adds complexity to it).

**Comment by JingukKim** [comment]
Thank you.
