### ISSUE TITLE
Train on custom dataset for panoptic segmentation

### ISSUE THREAD

**Issue by JasonRichard** [facebookresearch/Mask2Former#30]
I‘ve been trying to used it for a nuclei panoptic segmentation task.
Dataset is prepared like ADE20K panoptic do.
However, in evalutaion, it doesn't proposed any instance after a period time of training.

> File "/home/---/anaconda3/envs/mask2former/lib/python3.8/site-packages/panopticapi/evaluation.py", line 224, in pq_compute
    results[name], per_class_results = pq_stat.pq_average(categories, isthing=isthing) 
  File "/home/---/anaconda3/envs/mask2former/lib/python3.8/site-packages/panopticapi/evaluation.py", line 73, in pq_average
    return {'pq': pq / n, 'sq': sq / n, 'rq': rq / n, 'n': n}, per_class_results
ZeroDivisionError: division by zero

There several possible reasons accounting for it I assume:
- **Dataset not well prepared**: Are semantic and instance images label **folder** a must for panoptic? The labeled data I owned is not Detectorn2 format. But I referred to `prepare_ade20k_sem_seg`, `prepare_ade20k_ins_seg` and `prepare_ade20k_pan_seg`. Converted the labeled data to panoptic images (in a folder) and label json file. Commented the line `"sem_seg_file_name": sem_label_file,` in `dataset_dict`. 
- **Configure file not well modified**: Another reason maybe model not convergen. Is there any **configuration like Mask-RCNN's `anchor size` or `ratio`** in panopitc segmentation? Because nuclei in whole slide images (crop multiple patches in size 256\*256, with one nuclei around (8\~16)\*(8\~16) pixels) is rather small compared to common things in a natural image captioned by camera.

**Comment by bowenc0221** [comment]
The `ZeroDivisionError: division by zero` is because `n` (number of classes) is zero in your defined dataset. Please check your data is in the COCO panoptic segmentation format: https://cocodataset.org/#format-data

**Comment by JasonRichard** [comment]
Thanks for replying. 
>>
I find out what happened, but am still confused. 
My data is in the COCO panoptic segmentation format. And training schedule seems alright.
The problem lies in that `n` in `panopticapi.evaluation.pq_average` is not increased due to an empty prediction. 
(where all of catagories skipping `n += 1` because of `tp + fp + fn == 0:  continue`). I will report this to `panopticapi`. 
>>
But I still wonder how to prevent emtpy predition from the `mask2former` model.
It looks like following. I am still confused about 
```json
{       
        "images": [...],
        "annotations": [
                {
                    "image_id": "0012",
                    "file_name": "0012.png",
                    "segments_info": []
                },...
        ],
        "categories": [...]
}
```

``` python
def pq_average(self, categories, isthing):
    pq, sq, rq, n = 0, 0, 0, 0
    per_class_results = {}
    for label, label_info in categories.items():
        if isthing is not None:
            cat_isthing = label_info['isthing'] == 1
            if isthing != cat_isthing:
                continue
        iou = self.pq_per_cat[label].iou
        tp = self.pq_per_cat[label].tp
        fp = self.pq_per_cat[label].fp
        fn = self.pq_per_cat[label].fn
>>        if tp + fp + fn == 0:
>>            per_class_results[label] = {'pq': 0.0, 'sq': 0.0, 'rq': 0.0}
>>            continue
>>        n += 1
        pq_class = iou / (tp + 0.5 * fp + 0.5 * fn)
        sq_class = iou / tp if tp != 0 else 0
        rq_class = tp / (tp + 0.5 * fp + 0.5 * fn)
        per_class_results[label] = {'pq': pq_class, 'sq': sq_class, 'rq': rq_class}
        pq += pq_class
        sq += sq_class
        rq += rq_class

    return {'pq': pq / n, 'sq': sq / n, 'rq': rq / n, 'n': n}, per_class_results
```

**Comment by JasonRichard** [comment]
I'm also curious about the following configuration in `config/*.yaml`
Does it mean that, when two bbox overlap to a certain extend, smaller one will be suppress ?
>>
For my own dataset and task, stuff (isthing=0) category will always occupy most of the picture, with thing(instance) ones drenched in it. While some instances will also overlap with each other.
```yaml
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: False
      PANOPTIC_ON: True
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
```

Best regards ~

**Comment by bowenc0221** [comment]
The overlap is calculated with mask instead of box.

**Comment by unanan** [comment]
@JasonRichard Hi! Did you resolve this problem?
