### ISSUE TITLE
ImportError: .../MultiScaleDeformableAttention.cpython-38-X86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8dataptrIdEEPT_v

### ISSUE THREAD

**Issue by Wenzhiqiang16** [facebookresearch/Mask2Former#31]
Hello! Thank you for sharing.
I follow your **Example conda environment setup:**
![image](https://user-images.githubusercontent.com/29689120/148908594-119c20e4-8d48-4f88-9ca0-f364bed3ea88.png)
But when I run the code:
![image](https://user-images.githubusercontent.com/29689120/148908764-f70d5ef7-3e79-4479-9681-f6305ca0292d.png)
It doesnt work successifully. It makes an ImportError
![image](https://user-images.githubusercontent.com/29689120/148908900-f2fc3ea1-c7b8-41a3-9a27-96e4c1d3eb1b.png)

**Comment by bowenc0221** [comment]
This is related to compiling MultiScaleDeformableAttention, please refer to Deformable DETR (https://github.com/fundamentalvision/Deformable-DETR/issues?q=is%3Aissue+undefined+symbol+is%3Aclosed) for help.

**Comment by Wenzhiqiang16** [comment]
> This is related to compiling MultiScaleDeformableAttention, please refer to Deformable DETR (https://github.com/fundamentalvision/Deformable-DETR/issues?q=is%3Aissue+undefined+symbol+is%3Aclosed) for help.

got it，thank you

**Comment by rmanzanedo** [comment]
> Hello! Thank you for sharing. I follow your **Example conda environment setup:** ![image](https://user-images.githubusercontent.com/29689120/148908594-119c20e4-8d48-4f88-9ca0-f364bed3ea88.png) But when I run the code: ![image](https://user-images.githubusercontent.com/29689120/148908764-f70d5ef7-3e79-4479-9681-f6305ca0292d.png) It doesnt work successifully. It makes an ImportError ![image](https://user-images.githubusercontent.com/29689120/148908900-f2fc3ea1-c7b8-41a3-9a27-96e4c1d3eb1b.png)

Have you solved it? Thanks!

**Comment by rmanzanedo** [comment]
@Wenzhiqiang16  Have you solved it? Thanks!

**Comment by Wenzhiqiang16** [comment]
> @Wenzhiqiang16 Have you solved it? Thanks!

follow the "Example conda environment setup". The version of pytorch should be the same as your cuda. Pay attention, before "sh make.sh", you should run "export CUDA_HOME=/usr/local/'YOUR CUDA version'"

**Comment by Masrur02** [comment]
Hi,

Will it work for CUDA 11.8? The torch version for CUDA 11.8 starts from 2. 

TIA
