### ISSUE TITLE
How to visualize the VIS results?

### ISSUE THREAD

**Issue by wjn922** [facebookresearch/Mask2Former#33]
Hi,

Thanks for your wonderful work and repo.

Could you please provide the instructions on how to visualize the video instance segmentation results on images or videos? Thanks!

**Comment by bowenc0221** [comment]
You can use the demo to visualize VIS predictions: https://github.com/facebookresearch/Mask2Former/tree/main/demo_video

**Comment by XiongweiWu** [comment]
@bowenc0221 Hi, how do you visualize the gt as the figures in your appendix? I use the default script (visualize_data.py) of detection2 but the color seems different.

**Comment by wjn922** [comment]
> [](https://github.com/facebookresearch/Mask2Former/tree/main/demo_video)

Got it. Thanks.

**Comment by bowenc0221** [comment]
@XiongweiWu Figures in my paper are generated with customized code. You can use `overlay_instances` in https://github.com/facebookresearch/detectron2/blob/cb92ae1763cd7d3777c243f07749574cdaec6cb8/detectron2/utils/visualizer.py#L607 to control the color.
