### ISSUE TITLE
why i always got "detected 10 instances per frame"?

### ISSUE THREAD

**Issue by luolugithub** [facebookresearch/Mask2Former#35]
when i finetuning on my own ytv2021 dataset, i always got "detected 10 instances per frame",why????    trained model?

**Comment by bowenc0221** [comment]
https://github.com/facebookresearch/Mask2Former/blob/35758f3411532c6fc72d5d95b8c435409beed79e/mask2former_video/video_maskformer_model.py#L259-L260
