### ISSUE TITLE
Ade20k Panoptic Segmentation demo problem

### ISSUE THREAD

**Issue by paussus** [facebookresearch/Mask2Former#40]
Hi,

  I have a problem trying to use the demo with Ade20k Panoptic Segmentation. The command used is:

```
python demo.py --config-file ../configs/ade20k/panoptic-segmentation/maskformer2_R50_bs16_160k.yaml \
  --video-input ... \
  --output ... \
  --opts MODEL.WEIGHTS ../models/model_final_5c90d4.pkl
```

  And the stack trace is:

```
  File "demo.py", line 182, in <module>
    for vis_frame in tqdm.tqdm(demo.run_on_video(video), total=num_frames):
  File "/home/master/Develop/Mask2Former/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/master/Develop/Mask2Former/demo/predictor.py", line 130, in run_on_video
    yield process_predictions(frame, self.predictor(frame))
  File "/home/master/Develop/Mask2Former/demo/predictor.py", line 94, in process_predictions
    vis_frame = video_visualizer.draw_panoptic_seg_predictions(
  File "/home/master/Develop/Mask2Former/lib/python3.8/site-packages/detectron2/utils/video_visualizer.py", line 172, in draw_panoptic_seg_predictions
    labels = [self.metadata.thing_classes[k] for k in category_ids]
  File "/home/master/Develop/Mask2Former/lib/python3.8/site-packages/detectron2/utils/video_visualizer.py", line 172, in <listcomp>
    labels = [self.metadata.thing_classes[k] for k in category_ids]
IndexError: list index out of range
```

  I think I have found the source of the problem in [the lines](https://github.com/facebookresearch/Mask2Former/blob/161be514814ea63440fae520d2ec72707b62ba54/mask2former/data/datasets/register_ade20k_panoptic.py#L334)
```
    thing_classes = [k["name"] for k in ADE20K_150_CATEGORIES if k["isthing"] == 1]
    thing_colors = [k["color"] for k in ADE20K_150_CATEGORIES if k["isthing"] == 1]
```

of mask2former/data/datasets/register_ade20k_panoptic.py

  And from my understanding it happens because Detectron2 seems to use the id as the index, but these lines remove some items and the index to id mapping is lost.

Changing the lines to
```
    thing_classes = [k["name"] for k in ADE20K_150_CATEGORIES]
    thing_colors = [k["color"] for k in ADE20K_150_CATEGORIES]
```
seems to work, but I don't know if there are any undesired consequences.

I have installed Detectron2 with pip, but the line where the error happens appears to be also in the [git version](https://github.com/facebookresearch/detectron2/blob/25b4a23704960544fa7ab0a8bbc21f6a42bf8e0b/detectron2/utils/video_visualizer.py#L196).

**Comment by bowenc0221** [comment]
These changes will only affect visualization if you do not need to get instance segmentation of things only from a panoptic segmentation model.

**Comment by sidml** [comment]
I also got this error.
The fix suggested by @paussus works. I am not sure why the issue was closed when the issue still persists.

**Comment by RaghavPrabhakar66** [comment]
The issue is still there and the fix suggested by @paussus works. I think the issue should be reopened until there is a permanent fix.

**Comment by ChunyangYuan** [comment]
This issue is still there! (2024.08.04. ) Thank you @paussus !
