### ISSUE TITLE
Mapillary instance annotation?

### ISSUE THREAD

**Issue by wjn922** [facebookresearch/Mask2Former#44]
Hi, 

Thanks for your wonderful repo. I follow the steps in preparing datasets, but it seems that datasets/prepare_mapillary_vistas_ins_seg.py is not provided. Could you pls check it out?

**Comment by launchauto** [comment]
I also meet  the problems. It seems datasets/prepare_mapillary_vistas_ins_seg.py is not provided.

**Comment by bowenc0221** [comment]
The current code does not support instance segmentation on mapillary vistas. Because converting mapillary vistas to COCO-style annotation is very inefficient due to high resolution.

**Comment by wjn922** [comment]
OK, thanks.
