### ISSUE TITLE
modifying  MODEL.MASK_FORMER.NUM_OBJECT_QUERIES can't load pretrained model when training

### ISSUE THREAD

**Issue by FrankFang0813** [facebookresearch/Mask2Former#47]
Thanks for your code. I find that I can save GPU memory with modifying   MODEL.MASK_FORMER.NUM_OBJECT_QUERIES when running demo.py.  But after modifying that, I can't load pretrained model when training. Can you give me Any suggestion about this?

**Comment by bowenc0221** [comment]
The pre-trained model won't work if `MODEL.MASK_FORMER.NUM_OBJECT_QUERIES` is modified. You will need to train the model again if you want to use different `MODEL.MASK_FORMER.NUM_OBJECT_QUERIES`.

**Comment by FrankFang0813** [comment]
@bowenc0221 Thanks for your answer.

But I got this error.
```
RuntimeError: Error(s) in loading state_dict for MaskFormer:
        size mismatch for sem_seg_head.predictor.query_feat.weight: copying a param with shape torch.Size([100, 256]) from checkpoint, the shape in current model is torch.Size([30, 256]).
```
I use pre-trained model weights to train my custom dataset, and I modified MODEL.MASK_FORMER.NUM_OBJECT_QUERIES = 30 , but it dosen't work. So you mean that I can't use pre-trained model to fine tune on my custom dataset?

**Comment by bowenc0221** [comment]
As the error suggests, the pre-trained model you use has 100 queries instead of 30.
