### ISSUE TITLE
Does MaskFormer support multi-scale testing for VIS task?

### ISSUE THREAD

**Issue by wenhe-jia** [facebookresearch/Mask2Former#50]
Appreciate to your excellent work! I wonder whether you have tried some testing skills like multi-scale testing which may boost the final performance. Or does the implementation of Mask2Former in this repo support multi-scale testing on ytvis 2019/2021?

**Comment by bowenc0221** [comment]
No, multi-scale test is not supported and I have not tried it.

**Comment by wenhe-jia** [comment]
> No, multi-scale test is not supported and I have not tried it.

Thank you very much, I have implemented multi-scale testing by my self

**Comment by jiangzhengkai** [comment]
@wenhe-jia could you share the multi-scale testing implementation?
