### ISSUE TITLE
ValueError: matrix contains invalid numeric entries

### ISSUE THREAD

**Issue by EnnioEvo** [facebookresearch/Mask2Former#58]
I am just trying ti replicate the training on the panoptic coco dataset with

`python3 train_net.py --config-file configs/coco/panoptic-segmentation/maskformer2_R50_bs16_50ep.yaml --num-gpus 1 SOLVER.IMS_PER_BATCH 1 SOLVER.BASE_LR 0.1`

but I get the error you can see at the end of the output:

> [03/02 13:06:22 mask2former.data.dataset_mappers.coco_panoptic_new_baseline_dataset_mapper]: [COCOPanopticNewBaselineDatasetMapper] Full TransformGens used in training: [RandomFlip(), ResizeScale(min_scale=0.1, max_scale=2.0, target_height=1024, target_width=1024), FixedSizeCrop(crop_size=(1024, 1024))]
> [03/02 13:06:28 d2.data.build]: Using training sampler TrainingSampler
> [03/02 13:06:28 d2.data.common]: Serializing 118287 elements to byte tensors and concatenating them all ...
> [03/02 13:06:29 d2.data.common]: Serialized dataset takes 84.83 MiB
> [03/02 13:06:29 fvcore.common.checkpoint]: [Checkpointer] Loading from detectron2://ImageNetPretrained/torchvision/R-50.pkl ...
> [03/02 13:06:29 fvcore.common.checkpoint]: Reading a file from 'torchvision'
> [03/02 13:06:29 d2.checkpoint.c2_model_loading]: Following weights matched with submodule backbone:
> 
> WARNING [03/02 13:06:29 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
> criterion.empty_weight
> sem_seg_head.pixel_decoder.adapter_1.norm.{bias, weight}
> [...]
> sem_seg_head.predictor.transformer_self_attention_layers.8.self_attn.{in_proj_bias, in_proj_weight}
> WARNING [03/02 13:06:29 fvcore.common.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
>   stem.fc.{bias, weight}
> [03/02 13:06:29 d2.engine.train_loop]: Starting training from iteration 0
> /home/vision/Documents/Ennio/git/Mask2Former/mask2former/modeling/transformer_decoder/position_encoding.py:41: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
>   dim_t = self.temperature ** (2 * (dim_t // 2) / self.num_pos_feats)
> /home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/aten/src/ATen/native/TensorShape.cpp:2157.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> /home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:129: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
>   warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
> ERROR [03/02 13:06:36 d2.engine.train_loop]: Exception during training:
> Traceback (most recent call last):
>   File "/home/vision/Documents/Ananthu/detectron2/detectron2/engine/train_loop.py", line 149, in train
>     self.run_step()
>   File "/home/vision/Documents/Ananthu/detectron2/detectron2/engine/defaults.py", line 494, in run_step
>     self._trainer.run_step()
>   File "/home/vision/Documents/Ananthu/detectron2/detectron2/engine/train_loop.py", line 395, in run_step
>     loss_dict = self.model(data)
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/vision/Documents/Ennio/git/Mask2Former/mask2former/maskformer_model.py", line 209, in forward
>     losses = self.criterion(outputs, targets)
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/vision/Documents/Ennio/git/Mask2Former/mask2former/modeling/criterion.py", line 222, in forward
>     indices = self.matcher(outputs_without_aux, targets)
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/vision/Documents/Ennio/git/Mask2Former/mask2former/modeling/matcher.py", line 179, in forward
>     return self.memory_efficient_forward(outputs, targets)
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/vision/Documents/Ennio/git/Mask2Former/mask2former/modeling/matcher.py", line 151, in memory_efficient_forward
>     indices.append(linear_sum_assignment(C))
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/scipy/optimize/_lsap.py", line 100, in linear_sum_assignment
>     return _lsap_module.calculate_assignment(cost_matrix)
> ValueError: matrix contains invalid numeric entries
> [03/02 13:06:36 d2.engine.hooks]: Overall training speed: 5 iterations in 0:00:04 (0.8482 s / it)
> [03/02 13:06:36 d2.engine.hooks]: Total training time: 0:00:04 (0:00:00 on hooks)
> [03/02 13:06:36 d2.utils.events]:  eta: 3 days, 13:16:31  iter: 7  total_loss: 185.6  loss_ce: 10.52  loss_mask: 5.53  loss_dice: 4.719  loss_ce_0: 9.882  loss_mask_0: 2.379  loss_dice_0: 4.642  loss_ce_1: 9.742  loss_mask_1: 1.997  loss_dice_1: 4.629  loss_ce_2: 9.52  loss_mask_2: 2.539  loss_dice_2: 4.65  loss_ce_3: 9.885  loss_mask_3: 2.152  loss_dice_3: 4.731  loss_ce_4: 10.25  loss_mask_4: 4.738  loss_dice_4: 4.718  loss_ce_5: 10.36  loss_mask_5: 3.325  loss_dice_5: 4.717  loss_ce_6: 10.94  loss_mask_6: 3.435  loss_dice_6: 4.713  loss_ce_7: 10.55  loss_mask_7: 4.254  loss_dice_7: 4.704  loss_ce_8: 10.18  loss_mask_8: 5.652  loss_dice_8: 4.701  time: 0.8326  data_time: 0.0627  lr: 0.1  max_mem: 4355M
> Traceback (most recent call last):
>   File "/home/vision/Documents/Ennio/git/Mask2Former/train_net.py", line 321, in <module>
>     launch(
>   File "/home/vision/Documents/Ananthu/detectron2/detectron2/engine/launch.py", line 82, in launch
>     main_func(*args)
>   File "/home/vision/Documents/Ennio/git/Mask2Former/train_net.py", line 315, in main
>     return trainer.train()
>   File "/home/vision/Documents/Ananthu/detectron2/detectron2/engine/defaults.py", line 484, in train
>     super().train(self.start_iter, self.max_iter)
>   File "/home/vision/Documents/Ananthu/detectron2/detectron2/engine/train_loop.py", line 149, in train
>     self.run_step()
>   File "/home/vision/Documents/Ananthu/detectron2/detectron2/engine/defaults.py", line 494, in run_step
>     self._trainer.run_step()
>   File "/home/vision/Documents/Ananthu/detectron2/detectron2/engine/train_loop.py", line 395, in run_step
>     loss_dict = self.model(data)
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/vision/Documents/Ennio/git/Mask2Former/mask2former/maskformer_model.py", line 209, in forward
>     losses = self.criterion(outputs, targets)
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/vision/Documents/Ennio/git/Mask2Former/mask2former/modeling/criterion.py", line 222, in forward
>     indices = self.matcher(outputs_without_aux, targets)
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/vision/Documents/Ennio/git/Mask2Former/mask2former/modeling/matcher.py", line 179, in forward
>     return self.memory_efficient_forward(outputs, targets)
>   File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/vision/Documents/Ennio/git/Mask2Former/mask2former/modeling/matcher.py", line 151, in memory_efficient_forward
>     indices.append(linear_sum_assignment(C))
>   **File "/home/vision/anaconda3/envs/ananthu_venv/lib/python3.9/site-packages/scipy/optimize/_lsap.py", line 100, in linear_sum_assignment**
>     **return _lsap_module.calculate_assignment(cost_matrix)**
> **ValueError: matrix contains invalid numeric entries**

 Does anybody know what can be the problem?

**Comment by EnnioEvo** [comment]
Lowering the learning rate from 0.1to 0.001 solved the problem, I think the algorithm was just diverging

**Comment by Bowa529** [comment]
I haven't solved this problem yet, I set the base lr to 0.0001 during training, do I need to adjust it to 0.001? Or what other reasons?

**Comment by lx709** [comment]
I changed my learning rate from 0.001 to 0.0001, but the issue still happens after several training epoches.

**Comment by Ghy1209** [comment]
can you solve the problem？ I have this problem too

**Comment by rydenisbak** [comment]
you have **nan** value in cost, may be some bug, i suggest this temporary fix
```
python
cost[cost.isnan()] = 1e6
```

**Comment by SergiyShebotnov** [comment]
> you have **nan** value in cost, may be some bug, i suggest this temporary fix
> 
> ```
> python
> cost[cost.isnan()] = 1e6
> ```

Where would one define it?

**Comment by captainfffsama** [comment]
It seems that when `outmask` from float16 to float32, sometimes some value will be `inf`.After `batch_sigmoid_ce_loss_jit`, cost_mask will have Nan.
https://github.com/facebookresearch/Mask2Former/blob/9b0651c6c1d5b3af2e6da0589b719c514ec0d69a/mask2former/modeling/matcher.py#L135.

According @rydenisbak  answer, add `cost_mask[cost_mask.isnan()]=1e6` at https://github.com/facebookresearch/Mask2Former/blob/9b0651c6c1d5b3af2e6da0589b719c514ec0d69a/mask2former/modeling/matcher.py#L139 may temporary fix
