### ISSUE TITLE
is there any wrong with the table in paper?

### ISSUE THREAD

**Issue by Sunting78** [facebookresearch/Mask2Former#6]
1. PQ column: 50.7 51.2(-0.7) ? I guess the PQ is 51.9 on first row？
2. another question: If train the same epoch with htc++ or knet， the result is also better or not ?
![image](https://user-images.githubusercontent.com/18344247/145534650-3c47e46d-ce76-416d-a218-a96520d8fb11.png)

**Comment by bowenc0221** [comment]
1. You are correct, the first row of Table 4 (b) should be the same as the first row of Table 4 (a). I will update the ArXiv pdf when I get time.
2. I have not tried to train it with the same epoch as HTC++ or K-Net.
