### ISSUE TITLE
How to jointly train YTVIS2021 and COCO pseudo vid dataset for video instance segmentation?

### ISSUE THREAD

**Issue by wenhe-jia** [facebookresearch/Mask2Former#60]
Appreciate for your excellent work! Will you release the code for training video instance segmentation model on joint dataset of ytvis and coco pseudo video dataset? 

I noticed that  there is a **CocoClipDatasetMapper** implementation, can you tell me how to use it?

**Comment by bowenc0221** [comment]
We did not jointly train the model on YTVIS2021 and COCO pseudo vid dataset. The `CocoClipDatasetMapper` is used by the IFC code to pre-train there model on COCO but we do not need it anymore.
