### ISSUE TITLE
Implement Transfer Learning API / Instructions

### ISSUE THREAD

**Issue by lapp0** [facebookresearch/Mask2Former#69]
It would be helpful if we could piggy back on your library of pre-trained model for transfer learning. Perhaps this may be accomplished by freezing the first 6 (2L) of 9 layers of Mask2Formers transformer decoder.

Usage may look like this:

`export DETECTRON2_DATASETS=/path/to/dir/containing/new/dataset`

```
python train_net.py \
  --config-file <pretrained model config> \
  --pretrained-model /path/to/checkpoint_file
  --transfer-learning-dataset <new dataset>
```

**Comment by bowenc0221** [comment]
I did not get the question. You can always finetune the model on your own dataset by registering it in Detectron2.

**Comment by lapp0** [comment]
Sorry I wasn't clear.

What I'm requesting is a feature similar to keras' `trainable` attribute which freezes the weights and biases of a layer if false. https://keras.io/guides/transfer_learning/#the-typical-transferlearning-workflow

I would like to use one of Mask2Formers pre-trained COCO models to learn features of smaller datasets.

**Comment by bowenc0221** [comment]
In PyTorch, you can freeze any parameter by setting its `require_grad` to `False`.

**Comment by lapp0** [comment]
I will experiment with freezing different layers. If I have any success I'll make a PR.

**Comment by jkim50104** [comment]
@lapp0 Where did you add the require_grad False to freeze the layers? And just from curiosity any results about freezing different layers?
