### ISSUE TITLE
why do we need to compile CUDA kernel for  MSDeformAttn?

### ISSUE THREAD

**Issue by seyeeet** [facebookresearch/Mask2Former#7]
can you please explain why do we need to compile to cuda kernel for MSDeformAttn?
I see we have a[ python file](https://github.com/facebookresearch/Mask2Former/blob/main/mask2former/modeling/pixel_decoder/ops/modules/ms_deform_attn.py) for it, I am not understanding why the compilation is needed?
Sorry I am not very familiar with the concept of why it would not work if we use the py functions without compiling
In what scenario I should generally compile the cuda kernel? because I never paid attention to it :/

really appreciate it if you can please explain the reason behind it.
Thanks a ton!

**Comment by bowenc0221** [comment]
Please refer to PyTorch tutorial for more information: https://pytorch.org/tutorials/advanced/cpp_extension.html

**Comment by seyeeet** [comment]
@bowenc0221  
Thanks for the reference, but this does not answer my question.
Would be necessary to compile the MSDeformAttn? what is the difference between the provided c++ version and the pytorch version?
