### ISSUE TITLE
OOM issue with swin large backbone

### ISSUE THREAD

**Issue by Christinepan881** [facebookresearch/Mask2Former#71]
When I train the video model with swin large backbone on YT-VIS2021, it shows CUDA OOM error. I trained on 8V100 32GB GPUs, and the config is the same as provided. Same error happens when training on COCO dataset with swin large backbone. 
Does that mean mask2former - swin large needs more GPU memory?
Thanks!

**Comment by bowenc0221** [comment]
It is trained on 16 V100 32GB GPUs.
