### ISSUE TITLE
How to train instance segmentation with mask on custom dataset?

### ISSUE THREAD

**Issue by sangtrx** [facebookresearch/Mask2Former#73]
I tried to train Mask2Former on my COCO format custom dataset (only 2 classes).

I use the config configs/coco/instance-segmentation/maskformer2_R50_bs16_50ep.yaml and change MODEL.SEM_SEG_HEAD.NUM_CLASSES to 2 but when I train there is no mask_loss

`[03/28 20:21:38 d2.utils.events]:  eta: 0:17:34  iter: 1259  total_loss: 0.3866  loss_cls: 0.04811  loss_box_reg: 0.06793  loss_rpn_cls: 
0.09609  loss_rpn_loc: 0.2071  time: 0.1192  data_time: 0.0018  lr: 1e-05  max_mem: 2555M`

after training, I tried to run demo and there are only bboxes.

**Comment by bowenc0221** [comment]
From the log, you seem to train a Faster R-CNN model.

**Comment by sangtrx** [comment]
> From the log, you seem to train a Faster R-CNN model.

can you show me how to train on instance segmentation task? I have checked the configs and found nothing.

**Comment by satpalsr** [comment]
Hey @sangtrx, did you solve it? When I try to run a demo with this custom-trained model, I only see bounding boxes and not instance masks.

**Comment by Jxzde** [comment]
@sangtrx ,I encountered the same problem as yours, how did you solve it?

**Comment by sushilkhadkaanon** [comment]
Hey @sangtrx , @sangtrx , @Jxzde were you guys able to train ?  Please help me out. Anything will be appreciated.

**Comment by Jxzde** [comment]
@sushilkhadkaanon I succeeded in training, but the model I trained for instance segmentation ran as a semantic segmentation result

**Comment by sushilkhadkaanon** [comment]
@Jxzde can you suggest to me all the changes you made? I couldn't find any resources on how to train on a custom dataset. 
Thanks!

**Comment by Jxzde** [comment]
@sushilkhadkaanon https://www.guyuehome.com/37167,你可以参考这个网站，它修改了train_net.py文件

**Comment by sushilkhadkaanon** [comment]
@Jxzde thanks but I'm not able to access the page.
<img width="1698" alt="Screenshot 2023-03-15 at 1 42 08 PM" src="https://user-images.githubusercontent.com/50844865/225247453-a9f7dcee-5546-4601-8c6a-22477d02925b.png">

**Comment by Jxzde** [comment]
@sushilkhadkaanon https://www.guyuehome.com/37167

**Comment by sushilkhadkaanon** [comment]
Yeah, It is working for me. Thanksss!

**Comment by Jxzde** [comment]
@sushilkhadkaanon Are the results of the instance segmentation model you trained with your own dataset correct? Why is my demo followed by the result of semantic segmentation?

**Comment by sushilkhadkaanon** [comment]
@Jxzde , yes, for me the results are instance segmentation although it detects 100 instances, while visualizing it shows only one (actual one) and others are very smaller regions. And there are no bounding boxes as well. What I suggest you is to look carefully in your custom config file. 
The base should be an instance segmentation model config like this : 
`_BASE_: "coco/instance-segmentation/maskformer2_R50_bs16_50ep.yam`

And also try  adding this :

`INPUT:   
       DATASET_MAPPER_NAME: "mask_former_instance" #or "coco_instance_lsj"`
Be careful of indentation in config file.

**Comment by Jxzde** [comment]
@sushilkhadkaanon in your dataset. Do tags of the same category have the same name? For example, if there are multiple people in a picture, should they be labeled person1, person2, person3... or should they all be labeled person
