### ISSUE TITLE
The Result of instance-segmentation for Ade20K

### ISSUE THREAD

**Issue by xzz777** [facebookresearch/Mask2Former#75]
I can't find out the Result of instance-segmentation/panoptic-segmentation for Ade20K. Have you conduct these experiments? Could you provide the Result? I want to compare the result with my reproducing. Thanks a lot.

**Comment by lapp0** [comment]
This? https://github.com/facebookresearch/Mask2Former/blob/main/MODEL_ZOO.md#ade20k-model-zoo

**Comment by xzz777** [comment]
> This? https://github.com/facebookresearch/Mask2Former/blob/main/MODEL_ZOO.md#ade20k-model-zoo

I forget that, Thanks very much!
