### ISSUE TITLE
reproduction of Panoptic segmentation on COCO

### ISSUE THREAD

**Issue by wmkai** [facebookresearch/Mask2Former#79]
Hi thank you for your excellent work. I meet a problem when re-run your experiments.

I tried to follow your advice in [Getting Started with Mask2Former](https://github.com/facebookresearch/Mask2Former/blob/main/GETTING_STARTED.md), and run:
`python train_net.py --num-gpus 8 \
  --config-file configs/coco/panoptic-segmentation/maskformer2_R50_bs16_50ep.yaml`
after training, the log showed that "Start inference on 625 batches". But after a few days, there are still no new logs. So I kill this process and run
`python train_net.py \             
  --config-file configs/coco/panoptic-segmentation/maskformer2_R50_bs16_50ep.yaml \
  --eval-only MODEL.WEIGHTS ./output/model_0094999.pth`,
after evaluation, it showed that the result was
<img width="936" alt="image" src="https://user-images.githubusercontent.com/39148461/162377921-cf5df93f-29a1-4db9-be45-79736bc43435.png">
was lower that the result from Table 1 in the paper,
<img width="925" alt="image" src="https://user-images.githubusercontent.com/39148461/162410081-b8d387c9-a2fb-4864-958b-ccd280a3d960.png">
 could you help me see what is the reason for this ^ ^

**Comment by bowenc0221** [comment]
Your training did not finish, please refer to https://github.com/facebookresearch/Mask2Former/issues/74

**Comment by wmkai** [comment]
thx for replying, but my problem seems not the same as https://github.com/facebookresearch/Mask2Former/issues/74. His pytorch nccl and system nccl version numbers are not the same but mine are the same. Everytime after iteration 94979, my training process stop. At the same time, all my 8 GPUs are utilized 0% which is not the same with https://github.com/facebookresearch/Mask2Former/issues/74.

**Comment by bowenc0221** [comment]
The COCO model is trained for `368750` iterations, but you evaluated the model on the `94999`-th iteration.

**Comment by wmkai** [comment]
thanks, I tried again and find these logs after the `94999`-th iteration
<img width="605" alt="image" src="https://user-images.githubusercontent.com/39148461/162600660-078690ba-3457-4b05-a3a9-ddb0dcea48b4.png">
<img width="608" alt="image" src="https://user-images.githubusercontent.com/39148461/162600662-1f2b23ca-3a04-488a-86a8-e28834521149.png">
is there something wrong with my environment?

**Comment by wmkai** [comment]
it seems that I met this problem in https://github.com/open-mmlab/mmdetection/pull/7538
