### ISSUE TITLE
Training time for ADE20K semantic segmentation with swin tiny

### ISSUE THREAD

**Issue by YellowPig-zp** [facebookresearch/Mask2Former#81]
Hi Bowen, thank you for the great work! I am wondering what is an estimated training time for ade20k semantic segmentation with swin tiny backbone with your setup(8 V100 GPUs)? Thank you in advance!

**Comment by bowenc0221** [comment]
Sorry, I don't remember the training time but it should not be more than 2 days. The log will give you an estimate once you launch the job.

**Comment by YellowPig-zp** [comment]
Roughly takes ~16 with my own experience
