### ISSUE TITLE
problem with train_net_video.py

### ISSUE THREAD

**Issue by lywang76** [facebookresearch/Mask2Former#92]
When i trained youtube video data 2019, i got the following errors.

File "/Mask2Former/mask2former_video/modeling/matcher.py", line 141, in memory_efficient_forward
    cost_dice = batch_dice_loss_jit(out_mask, tgt_mask)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Global alloc not supported yet

How to solve it?

**Comment by lywang76** [comment]
Solved the problem by modifying modeling/match.py code.

**Comment by rumsyx** [comment]
Solved by this answer! https://github.com/facebookresearch/Mask2Former/issues/4#issuecomment-1094163241

**Comment by Robotatron** [comment]
> Solved the problem by modifying modeling/match.py code.

Good for you. How did you fix it?

**Comment by Robotatron** [comment]
> Solved the problem by modifying modeling/match.py code.

@lywang76 this does not help anyone. How did you solve it?
