### ISSUE TITLE
curl to docker image returning 404

### ISSUE THREAD

**Issue by AndresPrada** [facebookresearch/Mask2Former#99]
Hi,

I'm trying to run the docker example image provided in `https://replicate.com/facebookresearch/mask2former`. I'm able to run successfully the docker image but I'm unable to curl it. I keep getting `"POST /predict HTTP/1.1" 404 Not Found`. 

I attach a screenshot of my problem. Any help would be highly appreciated.

Thank you in advance!

![Screenshot from 2022-05-20 16-31-43](https://user-images.githubusercontent.com/19572861/169550243-de716804-76b1-459b-86f8-05d2f78890d7.png)

**Comment by Robotatron** [comment]
Did you solve the issue? 
Also, where can I download the docker file or image from replicate?

**Comment by Robotatron** [comment]
Please post the code for the docker file @AndresPrada 
It seems this repo does not contain one

**Comment by AndresPrada** [comment]
I did this some months ago and, since I never got a reply, I switched how I accessed the code: building from source with no docker container. Unfortunately, I no longer have the code nor remember what I did specifically for that case. Sorry!
